name: weather
description: "A weather app"
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: any
  flutter_bloc: ^8.1.3
  go_router: ^10.2.0
  injectable: ^2.3.1
  collection: ^1.17.1
  bloc: ^8.1.2
  freezed_annotation: 2.4.1
  dio: ^5.4.1
  http: 1.2.2
  get_it: ^7.7.0
  intl: ^0.19.0
  lottie: ^3.1.2
  shared_preferences: ^2.2.3
  geolocator: ^13.0.1
  flutter_svg: ^2.0.10+1
  page_indicator_plus: ^1.0.4
  worldtime: ^1.2.2
  built_value: 8.9.2
  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  flutter_lints: ^3.0.0
  build_runner: ^2.1.2
  injectable_generator: ^2.4.1
  freezed: ^2.4.1
  built_value_generator: 8.9.2


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
